spring:
  application:
  name: spring-dto-pattern

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems
    username: springstudent
    password: springstudent

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

server:
  servlet:
    context-path: /v1-ems

